[skip ci] :green_heart: Use -B for api.py checkout (#81)
This should alleviate the errors we get when the branch already exists:

```
Run python api.py deploy --version main --repo-name libhal-arm-mcu
Cloning https://github.com/libhal/api.git into temporary directory...
Switching to branch: libhal-arm-mcu-main
Copying documentation from build/api/main to /tmp/tmpmafte93g/libhal-arm-mcu/main
Generated switcher.json for libhal-arm-mcu with 3 versions
Updating API repo's 'origin' to use access token
Pushing branch to remote...
Git error: Cmd('git') failed due to: exit code(1)
  cmdline: git push --set-upstream origin libhal-arm-mcu-main
  stderr: 'To https://github.com/libhal/api.git
 ! [rejected]        libhal-arm-mcu-main -> libhal-arm-mcu-main (non-fast-forward)
error: failed to push some refs to 'https://github.com/libhal/api.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. If you want to integrate the remote changes,
hint: use 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.'
```